id: P006907
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:00.915254
source_metadata:
  id: bdr:W2CZ6035
  title: འབྲི་གུང་པའི་གདན་རབས་མདོར་བསྡུས
  author: ''
  volumes:
    5832d88b911d45d98f77556ff901fc5e:
      image_group_id: I1KG1058
      title: ''
      volume_number: 1
      total_pages: 52
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
