id: P006907
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6035
  title: འབྲི་གུང་པའི་གདན་རབས་མདོར་བསྡུས
  author: ''
  volumes:
    5832d88b911d45d98f77556ff901fc5e:
      image_group_id: I1KG1058
      title: ''
      volume_number: 1
      total_pages: 52
      base_file: v001.txt
