id: I7E78D347
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:04:12+00:00'
last_modified: '2022-06-08T09:32:05.095422+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6035
  title: འབྲི་གུང་པའི་གདན་རབས་མདོར་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    420C:
      image_group_id: I1KG1058
      title: ''
      total_pages: 52
      order: 1
      base_file: 420C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
